version: "3.0"

services:

  apcupsd:
    container_name: apcupsd
    image: valmati/apcupsd:latest
    hostname: DeviceHostname
    environment:
      - TZ=Europe/Madrid
      - BOT_TOKEN=123:ABC
      - CHAT_ID=-123
      - HEALTH_CHECK=https://hc-ping.com/your_uuid
      - SCHEDULE=37 3 * * *
    volumes:
      - /tmp/apcupsd-docker:/tmp/apcupsd-docker
    devices:
      - /dev/hidraw0:/dev/hidraw0
      - /dev/usb/hiddev0:/dev/usb/hiddev0
    restart: unless-stopped
